### ISSUE TITLE
那么扩展在哪下载呢

### ISSUE THREAD

**Issue by Schin-7** [csfwff/hacpai-finishing#1]
xxx

**Comment by csfwff** [comment]
= = 额 访问[这个页面](https://hacpai.com/article/1560741792708)查看详细说明

**Comment by csfwff** [comment]
> xxx

= = 额 访问[这个页面](https://hacpai.com/article/1560741792708)查看详细说明

**Comment by Schin-7** [comment]
![image](https://user-images.githubusercontent.com/35031682/59599491-3d564600-9131-11e9-8410-3c6da4cac9e2.png)
这点不动嗷

**Comment by csfwff** [comment]
> ![image](https://user-images.githubusercontent.com/35031682/59599491-3d564600-9131-11e9-8410-3c6da4cac9e2.png)
> 这点不动嗷

不需要点，装好了进聊天室你就明白了

**Comment by Schin-7** [comment]
555聊天室在哪进

**Comment by csfwff** [comment]
> 555聊天室在哪进

https://hacpai.com/cr
